import type { InsertServiceDirectory } from "@shared/schema";

export const serviceDirectorySeed: InsertServiceDirectory[] = [
  // === STREAMING SERVICES ===
  {
    name: "Netflix",
    slug: "netflix",
    category: "streaming",
    websiteUrl: "https://netflix.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.netflix.com/cancelplan",
    pauseSupported: false,
    cancellationInstructions: "1. Go to Netflix.com and sign in\n2. Click your profile icon → Account\n3. Click 'Cancel Membership'\n4. Confirm cancellation",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Disney+",
    slug: "disney-plus",
    category: "streaming",
    websiteUrl: "https://disneyplus.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.disneyplus.com/account",
    pauseSupported: false,
    cancellationInstructions: "1. Go to DisneyPlus.com and sign in\n2. Click your profile → Account\n3. Click your subscription\n4. Select 'Cancel Subscription'",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Spotify",
    slug: "spotify",
    category: "streaming",
    websiteUrl: "https://spotify.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.spotify.com/account/subscription/",
    pauseSupported: false,
    cancellationInstructions: "1. Go to spotify.com/account\n2. Click 'Your plan'\n3. Click 'Change plan'\n4. Select 'Cancel Premium'",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Apple Music",
    slug: "apple-music",
    category: "streaming",
    websiteUrl: "https://music.apple.com",
    controlMethod: "concierge",
    pauseSupported: false,
    cancellationInstructions: "Requires cancellation through Apple ID settings on device or appleid.apple.com",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "apple_id"],
    conciergeEmailTemplate: "Subject: Subscription Cancellation Request\n\nDear Apple Support,\n\nI would like to cancel my Apple Music subscription associated with the following account:\n\nEmail: {{user_email}}\n\nPlease confirm the cancellation.\n\nBest regards",
    isVerified: true,
  },
  {
    name: "Amazon Prime",
    slug: "amazon-prime",
    category: "streaming",
    websiteUrl: "https://amazon.com/prime",
    controlMethod: "self_service",
    cancellationUrl: "https://www.amazon.com/gp/primecentral",
    pauseSupported: true,
    pauseInstructions: "1. Go to Amazon Prime membership page\n2. Click 'End Membership'\n3. Choose 'Pause' option if available",
    cancellationInstructions: "1. Go to amazon.com and sign in\n2. Go to Account & Lists → Prime Membership\n3. Click 'End Membership and Benefits'\n4. Follow the prompts to cancel",
    estimatedCancellationTime: "3 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "YouTube Premium",
    slug: "youtube-premium",
    category: "streaming",
    websiteUrl: "https://youtube.com/premium",
    controlMethod: "self_service",
    cancellationUrl: "https://www.youtube.com/paid_memberships",
    pauseSupported: true,
    pauseInstructions: "1. Go to youtube.com/paid_memberships\n2. Click 'Manage membership'\n3. Select 'Pause membership' and choose duration",
    cancellationInstructions: "1. Go to youtube.com/paid_memberships\n2. Click 'Manage membership'\n3. Click 'Deactivate' or 'Cancel'\n4. Confirm cancellation",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "HBO Max",
    slug: "hbo-max",
    category: "streaming",
    websiteUrl: "https://max.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.max.com/settings",
    pauseSupported: false,
    cancellationInstructions: "1. Go to max.com and sign in\n2. Go to Settings → Subscription\n3. Click 'Cancel Subscription'\n4. Confirm cancellation",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === SOFTWARE/PRODUCTIVITY ===
  {
    name: "Adobe Creative Cloud",
    slug: "adobe-creative-cloud",
    category: "software",
    websiteUrl: "https://adobe.com",
    controlMethod: "concierge",
    cancellationUrl: "https://account.adobe.com/plans",
    pauseSupported: false,
    cancellationInstructions: "Adobe has early termination fees. Contact support for best options.",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "account_number"],
    conciergeEmailTemplate: "Subject: Adobe Creative Cloud Cancellation Request\n\nDear Adobe Support,\n\nI would like to cancel my Adobe Creative Cloud subscription. My account details:\n\nEmail: {{user_email}}\n\nPlease advise on any early termination fees and process the cancellation.\n\nBest regards",
    conciergeMerchantEmail: "support@adobe.com",
    isVerified: true,
  },
  {
    name: "Microsoft 365",
    slug: "microsoft-365",
    category: "software",
    websiteUrl: "https://microsoft.com/microsoft-365",
    controlMethod: "self_service",
    cancellationUrl: "https://account.microsoft.com/services",
    pauseSupported: false,
    cancellationInstructions: "1. Go to account.microsoft.com/services\n2. Find Microsoft 365 subscription\n3. Click 'Manage'\n4. Select 'Cancel' and follow prompts",
    estimatedCancellationTime: "5 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Notion",
    slug: "notion",
    category: "software",
    websiteUrl: "https://notion.so",
    controlMethod: "api",
    apiProvider: "stripe",
    pauseSupported: true,
    cancellationUrl: "https://www.notion.so/profile",
    cancellationInstructions: "1. Go to notion.so/profile\n2. Click 'Settings & Members'\n3. Go to 'Plans'\n4. Click 'Downgrade' or 'Cancel'",
    estimatedCancellationTime: "1 minute",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Canva Pro",
    slug: "canva-pro",
    category: "software",
    websiteUrl: "https://canva.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.canva.com/settings/billing",
    pauseSupported: false,
    cancellationInstructions: "1. Go to canva.com and sign in\n2. Click Settings → Billing & plans\n3. Click 'Cancel subscription'\n4. Follow the prompts",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Canva",
    slug: "canva",
    category: "software",
    websiteUrl: "https://canva.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.canva.com/settings/billing",
    pauseSupported: false,
    cancellationInstructions: "1. Go to canva.com and sign in\n2. Click Settings → Billing & plans\n3. Click 'Cancel subscription'\n4. Follow the prompts",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Figma",
    slug: "figma",
    category: "software",
    websiteUrl: "https://figma.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.figma.com/settings",
    pauseSupported: false,
    cancellationInstructions: "1. Go to figma.com/settings\n2. Click 'Billing' tab\n3. Click 'Cancel plan'\n4. Confirm cancellation",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Google Workspace",
    slug: "google-workspace",
    category: "software",
    websiteUrl: "https://workspace.google.com",
    controlMethod: "self_service",
    cancellationUrl: "https://admin.google.com/ac/billing",
    pauseSupported: false,
    cancellationInstructions: "1. Go to admin.google.com\n2. Click Billing\n3. Select subscription\n4. Click 'Cancel subscription'",
    estimatedCancellationTime: "5 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Slack",
    slug: "slack",
    category: "software",
    websiteUrl: "https://slack.com",
    controlMethod: "self_service",
    cancellationUrl: "https://slack.com/admin/billing",
    pauseSupported: false,
    cancellationInstructions: "1. Go to slack.com workspace settings\n2. Click Billing\n3. Click 'Downgrade to Free'\n4. Confirm changes",
    estimatedCancellationTime: "3 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "iCloud Storage",
    slug: "icloud",
    category: "cloud_storage",
    websiteUrl: "https://apple.com/icloud",
    controlMethod: "concierge",
    pauseSupported: false,
    cancellationInstructions: "Cancel through Apple ID settings on device or appleid.apple.com",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "apple_id"],
    isVerified: true,
  },

  // === FITNESS ===
  {
    name: "Peloton",
    slug: "peloton",
    category: "fitness",
    websiteUrl: "https://onepeloton.com",
    controlMethod: "concierge",
    pauseSupported: true,
    pauseInstructions: "Contact Peloton support to pause membership (up to 3 months)",
    cancellationInstructions: "Must call Peloton support at 1-866-679-9129 or chat via app",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "phone"],
    conciergeEmailTemplate: "Subject: Peloton Membership Cancellation\n\nDear Peloton Support,\n\nI would like to cancel my Peloton membership.\n\nAccount email: {{user_email}}\n\nPlease process this cancellation request.\n\nBest regards",
    isVerified: true,
  },
  {
    name: "Strava",
    slug: "strava",
    category: "fitness",
    websiteUrl: "https://strava.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.strava.com/account/subscriptions",
    pauseSupported: false,
    cancellationInstructions: "1. Go to strava.com/account/subscriptions\n2. Click 'Cancel Subscription'\n3. Confirm cancellation",
    estimatedCancellationTime: "1 minute",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "MyFitnessPal",
    slug: "myfitnesspal",
    category: "fitness",
    websiteUrl: "https://myfitnesspal.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.myfitnesspal.com/account/subscriptions",
    pauseSupported: false,
    cancellationInstructions: "1. Go to myfitnesspal.com settings\n2. Navigate to Subscriptions\n3. Click 'Cancel Premium'\n4. Confirm",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === NEWS/MEDIA ===
  {
    name: "The New York Times",
    slug: "nytimes",
    category: "news",
    websiteUrl: "https://nytimes.com",
    controlMethod: "concierge",
    pauseSupported: true,
    pauseInstructions: "Call NYT customer service to pause delivery/digital access",
    cancellationInstructions: "Must call 1-800-591-9233 or chat with customer service",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "account_number"],
    conciergeEmailTemplate: "Subject: New York Times Subscription Cancellation\n\nDear NYT Customer Service,\n\nI would like to cancel my subscription.\n\nAccount email: {{user_email}}\n\nPlease process this cancellation.\n\nBest regards",
    isVerified: true,
  },
  {
    name: "The Wall Street Journal",
    slug: "wsj",
    category: "news",
    websiteUrl: "https://wsj.com",
    controlMethod: "concierge",
    pauseSupported: true,
    cancellationInstructions: "Must call customer service to cancel",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "account_number"],
    isVerified: true,
  },

  // === GAMING ===
  {
    name: "Xbox Game Pass",
    slug: "xbox-game-pass",
    category: "gaming",
    websiteUrl: "https://xbox.com/gamepass",
    controlMethod: "self_service",
    cancellationUrl: "https://account.microsoft.com/services",
    pauseSupported: false,
    cancellationInstructions: "1. Go to account.microsoft.com/services\n2. Find Xbox Game Pass\n3. Click 'Manage'\n4. Select 'Cancel' and follow prompts",
    estimatedCancellationTime: "3 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "PlayStation Plus",
    slug: "playstation-plus",
    category: "gaming",
    websiteUrl: "https://playstation.com",
    controlMethod: "self_service",
    cancellationUrl: "https://store.playstation.com/subscriptions",
    pauseSupported: false,
    cancellationInstructions: "1. Go to PlayStation Store → Subscription Management\n2. Select PlayStation Plus\n3. Click 'Turn Off Auto-Renew'",
    estimatedCancellationTime: "3 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === CLOUD STORAGE ===
  {
    name: "Dropbox",
    slug: "dropbox",
    category: "cloud_storage",
    websiteUrl: "https://dropbox.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.dropbox.com/account/plan",
    pauseSupported: false,
    cancellationInstructions: "1. Go to dropbox.com/account/plan\n2. Click 'Cancel plan'\n3. Follow the downgrade process",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Google One",
    slug: "google-one",
    category: "cloud_storage",
    websiteUrl: "https://one.google.com",
    controlMethod: "self_service",
    cancellationUrl: "https://one.google.com/settings",
    pauseSupported: false,
    cancellationInstructions: "1. Go to one.google.com/settings\n2. Click 'Cancel membership'\n3. Follow the prompts",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "iCloud+",
    slug: "icloud-plus",
    category: "cloud_storage",
    websiteUrl: "https://apple.com/icloud",
    controlMethod: "concierge",
    pauseSupported: false,
    cancellationInstructions: "Cancel through Apple ID settings on device or appleid.apple.com",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "apple_id"],
    isVerified: true,
  },

  // === VPN/SECURITY ===
  {
    name: "NordVPN",
    slug: "nordvpn",
    category: "security",
    websiteUrl: "https://nordvpn.com",
    controlMethod: "self_service",
    cancellationUrl: "https://my.nordaccount.com/dashboard/nordvpn/",
    pauseSupported: false,
    cancellationInstructions: "1. Go to my.nordaccount.com\n2. Navigate to your subscription\n3. Click 'Cancel Auto-Renewal'\n4. Confirm cancellation",
    estimatedCancellationTime: "3 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "1Password",
    slug: "1password",
    category: "security",
    websiteUrl: "https://1password.com",
    controlMethod: "self_service",
    cancellationUrl: "https://my.1password.com/settings/billing",
    pauseSupported: false,
    cancellationInstructions: "1. Go to my.1password.com/settings/billing\n2. Click 'Cancel subscription'\n3. Follow the prompts",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === DATING ===
  {
    name: "Tinder",
    slug: "tinder",
    category: "dating",
    websiteUrl: "https://tinder.com",
    controlMethod: "concierge",
    pauseSupported: false,
    cancellationInstructions: "If billed through App Store/Play Store, cancel there. Otherwise contact Tinder support.",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "phone"],
    isVerified: true,
  },
  {
    name: "Bumble",
    slug: "bumble",
    category: "dating",
    websiteUrl: "https://bumble.com",
    controlMethod: "concierge",
    pauseSupported: false,
    cancellationInstructions: "Cancel through App Store/Play Store subscription management",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === MULAH MERCHANT EXAMPLES ===
  {
    name: "Mulah Pro",
    slug: "mulah-pro",
    category: "software",
    websiteUrl: "https://mulah.app",
    controlMethod: "mulah_merchant",
    pauseSupported: true,
    pauseInstructions: "Instantly pause from within Mulah app",
    cancellationInstructions: "Instantly cancel from within Mulah app",
    estimatedCancellationTime: "Instant",
    requiredInfo: [],
    isVerified: true,
  },
  {
    name: "Gym Membership",
    slug: "gym-membership",
    category: "fitness",
    websiteUrl: "https://example-gym.com",
    controlMethod: "mulah_merchant",
    pauseSupported: true,
    pauseInstructions: "Instantly pause from within Mulah app",
    cancellationInstructions: "Instantly cancel from within Mulah app",
    estimatedCancellationTime: "Instant",
    requiredInfo: [],
    isVerified: true,
  },
  
  // === AI/SOFTWARE ===
  {
    name: "ChatGPT",
    slug: "chatgpt",
    category: "software",
    websiteUrl: "https://chat.openai.com",
    controlMethod: "self_service",
    cancellationUrl: "https://chat.openai.com/settings/subscription",
    pauseSupported: false,
    cancellationInstructions: "1. Go to chat.openai.com\n2. Click your profile → Settings\n3. Go to Subscription\n4. Click 'Cancel plan'",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "ChatGPT Plus",
    slug: "chatgpt-plus",
    category: "software",
    websiteUrl: "https://chat.openai.com",
    controlMethod: "self_service",
    cancellationUrl: "https://chat.openai.com/settings/subscription",
    pauseSupported: false,
    cancellationInstructions: "1. Go to chat.openai.com\n2. Click your profile → Settings\n3. Go to Subscription\n4. Click 'Cancel plan'",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "Dropbox Plus",
    slug: "dropbox-plus",
    category: "cloud_storage",
    websiteUrl: "https://dropbox.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.dropbox.com/account/plan",
    pauseSupported: false,
    cancellationInstructions: "1. Go to dropbox.com/account/plan\n2. Click 'Cancel plan'\n3. Follow the downgrade process",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === FOOD DELIVERY ===
  {
    name: "Uber Eats Pass",
    slug: "uber-eats-pass",
    category: "food_delivery",
    websiteUrl: "https://ubereats.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.ubereats.com/member",
    pauseSupported: false,
    cancellationInstructions: "1. Open Uber Eats app\n2. Go to Account → Uber Eats Pass\n3. Click 'Manage membership'\n4. Select 'Cancel membership'",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "DoorDash DashPass",
    slug: "doordash-dashpass",
    category: "food_delivery",
    websiteUrl: "https://doordash.com",
    controlMethod: "self_service",
    cancellationUrl: "https://www.doordash.com/consumer/membership/",
    pauseSupported: true,
    pauseInstructions: "1. Go to DoorDash app → Account\n2. Select DashPass\n3. Choose 'Pause membership'",
    cancellationInstructions: "1. Go to doordash.com/consumer/membership\n2. Click 'Manage DashPass'\n3. Select 'Cancel'\n4. Confirm",
    estimatedCancellationTime: "2 minutes",
    requiredInfo: ["email"],
    isVerified: true,
  },

  // === DEMO SHOWCASE SERVICES ===
  // These services demonstrate Mulah's advanced control capabilities
  
  {
    name: "StreamFlix",
    slug: "streamflix",
    category: "streaming",
    websiteUrl: "https://streamflix.demo",
    controlMethod: "api",
    apiProvider: "streamflix",
    pauseSupported: true,
    pauseInstructions: "Pause instantly through Mulah after connecting your account",
    cancellationInstructions: "Cancel instantly through Mulah after connecting your account",
    estimatedCancellationTime: "Instant (after account connection)",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "SkyShield Premium",
    slug: "skyshield-premium",
    category: "insurance",
    websiteUrl: "https://skyshield.demo",
    controlMethod: "concierge",
    pauseSupported: false,
    cancellationInstructions: "60-day notice required. Early termination fee applies based on remaining contract.",
    estimatedCancellationTime: "60 days notice period",
    requiredInfo: ["email", "policy_number"],
    isVerified: true,
  },
  {
    name: "UnityHub Family",
    slug: "unityhub-family",
    category: "telecom",
    websiteUrl: "https://unityhub.demo",
    controlMethod: "concierge",
    pauseSupported: true,
    pauseInstructions: "Individual lines can be paused. Primary account holder approval required.",
    cancellationInstructions: "Multi-line plans require primary holder authorization and individual line handling.",
    estimatedCancellationTime: "24-48 hours",
    requiredInfo: ["email", "phone", "account_number"],
    isVerified: true,
  },
  {
    name: "Pilates Loft Elite",
    slug: "pilates-loft-elite",
    category: "fitness",
    websiteUrl: "https://pilatesloft.demo",
    controlMethod: "concierge",
    pauseSupported: true,
    pauseInstructions: "Phone call required during business hours (M-F 10am-2pm only)",
    cancellationInstructions: "Must call during limited business hours. Missed window penalty may apply.",
    estimatedCancellationTime: "Phone call required - business hours only",
    requiredInfo: ["email", "phone", "member_id"],
    isVerified: true,
  },
  {
    name: "FusionStream Max",
    slug: "fusionstream-max",
    category: "streaming",
    websiteUrl: "https://fusionstream.demo",
    controlMethod: "concierge",
    pauseSupported: true,
    pauseInstructions: "Bundle includes Disney+, Hulu, ESPN+. Individual services can be managed.",
    cancellationInstructions: "Bundled services with loyalty points. Full cancel, downgrade, or split options available.",
    estimatedCancellationTime: "Multiple steps - 24-48 hours",
    requiredInfo: ["email"],
    isVerified: true,
  },
  {
    name: "TrialBox Creator",
    slug: "trialbox-creator",
    category: "software",
    websiteUrl: "https://trialbox.demo",
    controlMethod: "api",
    apiProvider: "trialbox",
    pauseSupported: false,
    cancellationInstructions: "Cancel before trial converts to €299/month",
    estimatedCancellationTime: "Instant",
    requiredInfo: ["email"],
    isVerified: true,
  },
];
